services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  kafka-1:
    image: apache/kafka:4.1.1
    container_name: kafka-1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092, CONTROLLER://0.0.0.0:9093, INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka-1:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093, 2@kafka-2:9093, 3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      CLUSTER_ID: "link-tracker-cluster"
    ports:
      - "9092:9092"
    volumes:
      - kafka_1_data:/var/lib/kafka/data

  kafka-2:
    image: apache/kafka:4.1.1
    container_name: kafka-2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094, CONTROLLER://0.0.0.0:9093, INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094, INTERNAL://kafka-2:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, CONTROLLER:PLAINTEXT, INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093, 2@kafka-2:9093, 3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      CLUSTER_ID: "link-tracker-cluster"
    ports:
      - "9094:9094"
    volumes:
      - kafka_2_data:/var/lib/kafka/data

  kafka-3:
    image: apache/kafka:4.1.1
    container_name: kafka-3
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9096, CONTROLLER://0.0.0.0:9093, INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9096, INTERNAL://kafka-3:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, CONTROLLER:PLAINTEXT, INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093, 2@kafka-2:9093, 3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      CLUSTER_ID: "link-tracker-cluster"
    ports:
      - "9096:9096"
    volumes:
      - kafka_3_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: link-tracker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:29092, kafka-2:29092, kafka-3:29092
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

  valkey-node-0:
    image: bitnamilegacy/valkey-cluster:latest
    container_name: valkey-node-0
    ports:
      - "6379:6379"
    volumes:
      - valkey_0_data:/bitnami/valkey/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2

  valkey-node-1:
    image: bitnamilegacy/valkey-cluster:latest
    container_name: valkey-node-1
    ports:
      - "6380:6379"
    volumes:
      - valkey_1_data:/bitnami/valkey/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2

  valkey-node-2:
    image: bitnamilegacy/valkey-cluster:latest
    container_name: valkey-node-2
    ports:
      - "6381:6379"
    volumes:
      - valkey_2_data:/bitnami/valkey/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2

  valkey-cluster-init:
    image: bitnamilegacy/valkey-cluster:latest
    container_name: valkey-cluster-init
    depends_on:
      - valkey-node-0
      - valkey-node-1
      - valkey-node-2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_CLUSTER_REPLICAS=0
      - VALKEY_CLUSTER_CREATOR=yes
      - VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2

  scrapper:
    build:
      context: .
      dockerfile: scrapper/Dockerfile
    container_name: scrapper
    ports:
      - "8081:8081"
    env_file:
      - scrapper/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/scrapper
      SPRING_DATA_REDIS_CLUSTER_NODES: valkey-node-0:6379,valkey-node-1:6379,valkey-node-2:6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-1:29092,kafka-2:29092,kafka-3:29092
      APP_BOT_BASE_URL: http://bot:8080
    depends_on:
      - db
      - kafka-1
      - kafka-2
      - kafka-3
      - valkey-cluster-init

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: bot
    ports:
      - "8080:8080"
    env_file:
      - bot/.env
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-1:29092,kafka-2:29092,kafka-3:29092
      APP_SCRAPPER_BASE_URL: http://scrapper:8081
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - scrapper

volumes:
  db_data:
  kafka_1_data:
  kafka_2_data:
  kafka_3_data:
  valkey_0_data:
  valkey_1_data:
  valkey_2_data:
