server:
  port: 8081

spring:
  application:
    name: scrapper
  config:
    import: optional:file:scrapper/.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

app:
  stackoverflow:
    key: ${STACKOVERFLOW_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    access-token: ${STACKOVERFLOW_ACCESS_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
  github:
    token: ${GITHUB_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
  bot:
    base-url: http://localhost:8080
  scheduler:
    interval: PT1M
  database:
    access-type: ORM # INMEMORY, SQL, ORM
