server:
  port: 8081

spring:
  application:
    name: scrapper
  config:
    import: optional:file:scrapper/.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092, localhost:9094, localhost:9096
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: false
        enable.idempotence: true
  data:
    redis:
      cluster:
        nodes: localhost:6379, localhost:6380, localhost:6381
      timeout: 2s
  cache:
    type: redis
    cache-names: links
    redis:
      time-to-live: PT5M
      key-prefix: "scrapper::"
      use-key-prefix: true

app:
  stackoverflow:
    key: ${STACKOVERFLOW_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    access-token: ${STACKOVERFLOW_ACCESS_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    connect-timeout: 5s
    read-timeout: 30s
  github:
    token: ${GITHUB_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    connect-timeout: 5s
    read-timeout: 30s
  bot:
    base-url: http://localhost:8080
    connect-timeout: 5s
    read-timeout: 30s
  scheduler:
    enabled: true
    interval: PT1M
    batch-size: 100
    thread-count: 4
  database:
    access-type: ORM # INMEMORY, SQL, ORM
  notification:
    transport: KAFKA # KAFKA, HTTP
  kafka:
    topic-name: link-updates
