server:
  port: 8080

spring:
  application:
    name: bot
  config:
    import: optional:file:bot/.env[.properties]
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "backend.academy.linktracker.*"
        spring.json.value.default.type: backend.academy.linktracker.bot.dto.LinkUpdate
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
  scrapper:
    base-url: http://localhost:8081
  notification:
    transport: KAFKA # KAFKA, HTTP
  kafka:
    topic-name: link-updates
    dlq-topic-name: link-updates-dlq
    consumer-group-id: bot-link-updates
    max-retries: 3
